### ISSUE TITLE
Card improvement

### ISSUE THREAD

**Issue by StrawHatHacker** [willpinha/daisy-collection#64]
### Description

`card` > `Article with image` 's user area should be the same as `card` > `article` 's user area (since it looks a bit nicer 🙂)

### Steps to reproduce (for bugs)

Hover over the user icons in both cards

### Screenshots or Error Messages (if applicable)

![image](https://github.com/willpinha/daisy-collection/assets/34351536/b3b492c8-f68c-4239-817e-12dddef2d696)
![image](https://github.com/willpinha/daisy-collection/assets/34351536/df3df01c-5641-403d-b5c6-3854d7c1ed2c)

**Comment by willpinha** [comment]
The card actually looks better using a ghost button instead of the link, in addition to being more consistent with the other cards

**Comment by willpinha** [comment]
Additionally, I will update the CONTRIBUTING guide to better define who works on which issue, and to also avoid duplicate work
